version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      API_HTTP_BASE_URL: "http://localhost:8000/api"
      API_WS_BASE_URL: "http://localhost:8000/ws"