name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: AKIAXGMJMOP3HCZOFNWN
            aws-secret-access-key: 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
            aws-region: us-east-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t esclender/doctums-front:latest

        - name: tag image before push to ECR
          id: tag-docker-image
          run: docker tag esclender/doctums-front:latest 494746235894.dkr.ecr.us-east-1.amazonaws.com/esclender/doctums:latest
        
        - name: push the docker image
          id: push-docker-image
          run: docker push 494746235894.dkr.ecr.us-east-1.amazonaws.com/esclender/doctums:latest